import { IProductProps } from 'components/common/productGridItem';

export const HEADER_FOOTER_CONTENT = 'HEADER_FOOTER_CONTENT';
export const VEHICLE_CARE_CONTENT = 'VEHICLE_CARE_CONTENT';
export const LOCATION_CONTENT = 'LOCATION_CONTENT';
export const HERO_PANEL_CONTENT = 'HERO_PANEL_CONTENT';
export const OFFERS_SECTION_CONTENT = 'OFFERS_SECTION_CONTENT';
export const CATEGORY_CONTENT_TYPE = 'CATEGORY_CONTENT_TYPE';
export const SUBSCRIPTION_CONTENT = 'SUBSCRIPTION_CONTENT';
export const OFFERS_SECTION_FILTERED_CONTENT = 'OFFERS_SECTION_FILTERED_CONTENT';
export const POPULAR_PRODUCTS_CONTENT = 'POPULAR_PRODUCTS_CONTENT';
export const PRODUCT_DETAILS_CONTENT = 'PRODUCT_DETAILS_CONTENT';
export const FAQS_CONTENT = 'FAQS_CONTENT';
export const ORDERS_CONTENT = 'ORDERS_CONTENT';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const LOCATION_DETAILS_CONTENT = 'LOCATION_DETAILS_CONTENT';
export const BLOG_CONTENT = 'BLOG_CONTENT';
export const TERMS_CONDITIONS = 'TERMS_CONDITIONS';
export const PRIVACY_POLICY = 'PRIVACY_POLICY';
export const CREATE_ORDER = 'CREATE_ORDER';

export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP';
export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';
export const CHECKOUT_JOURNEY = 'CHECKOUT_JOURNEY';
export const SET_WEEK_SLOTS = 'SET_WEEK_SLOTS';
export const SET_BOOKING_DATA = 'SET_BOOKING_DATA';
export const SET_BOOKING_CONTROLS = 'SET_BOOKING_CONTROLS';
export const REMOVE_BOOKING_DETAILS = 'REMOVE_BOOKING_DETAILS';
export const REMOVE_BOOKING_CONTROLS = 'REMOVE_BOOKING_CONTROLS';
export const SET_BOOKING_TIME_SLOTS_ONLY = 'SET_BOOKING_TIME_SLOTS_ONLY';
export const SET_BOOKING_LOCATIONS = 'SET_BOOKING_LOCATIONS';
export const SET_IS_CHECKOUT_VALID = 'SET_IS_CHECKOUT_VALID';

export const SET_COMPARABLE_ITEMS = 'SET_COMPARABLE_ITEMS';
export const REMOVE_COMPARABLE_ITEMS = 'REMOVE_COMPARABLE_ITEMS';
export const CHECK_CUSTOMER = 'CHECK_CUSTOMER';
export const PAYMENT_REQUEST_CONTENT = 'PAYMENT_REQUEST_CONTENT';
export interface ISetCompareItemsProps {
  products: IProductProps[];
  placeHolderCount: number;
}

export const OFFER_DETAILS_CONTENT = 'OFFER_DETAILS_CONTENT';
export const BRAND_DETAILS_CONTENT = 'BRAND_DETAILS_CONTENT';
export const SLOT_LOCATION_CONTENT = 'SLOT_LOCATION_CONTENT';
export const STOCK_QUANTITY_CONTENT = 'STOCK_QUANTITY_CONTENT';
export const PRODUCT_SERVICE_TIME = 'PRODUCT_SERVICE_TIME';
export const PRODUCT_STOCK = 'PRODUCT_STOCK';
export const SERVICE_SLOT_CONTENT = 'SERVICE_SLOT_CONTENT';
export const GETSLOT_CONTENT = 'GETSLOT_CONTENT';
export const UPDATE_SLOT = 'UPDATE_SLOT';
export const GETBAYSUBSLOT_CONTENT = 'GETBAYSUBSLOT_CONTENT';
export const GETBAY_SUBSLOT_ID = 'GETBAY_SUBSLOT_ID';
export const CHECK_LOCATION = 'CHECK_LOCATION';
export const CHECKOUT_JOURNEY_CONTENT = 'CHECKOUT_JOURNEY_CONTENT';
